"
I am a gap in the disk
"
Class {
	#name : 'Day9Gap',
	#superclass : 'Object',
	#instVars : [
		'gapSize',
		'position'
	],
	#category : 'AoCDay09',
	#package : 'AoCDay09'
}

{ #category : 'accessing' }
Day9Gap >> gapSize [

	^ gapSize
]

{ #category : 'accessing' }
Day9Gap >> gapSize: anObject [

	gapSize := anObject
]

{ #category : 'accessing' }
Day9Gap >> position [

	^ position
]

{ #category : 'accessing' }
Day9Gap >> position: anObject [

	position := anObject
]
