Class {
	#name : 'Day9Block',
	#superclass : 'Object',
	#instVars : [
		'blockSize',
		'position',
		'id'
	],
	#category : 'AoCDay9',
	#package : 'AoCDay9'
}

{ #category : 'accessing' }
Day9Block >> blockSize [

	^ blockSize
]

{ #category : 'accessing' }
Day9Block >> blockSize: anObject [

	blockSize := anObject
]

{ #category : 'accessing' }
Day9Block >> id [

	^ id
]

{ #category : 'accessing' }
Day9Block >> id: anObject [

	id := anObject
]

{ #category : 'accessing' }
Day9Block >> position [

	^ position
]

{ #category : 'accessing' }
Day9Block >> position: anObject [

	position := anObject
]
